PPW/urls.py
from django.urls import path
from . import views

app_name = 'PPW'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('organization/', views.more, name='more'),
]

Story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PPW.urls')),
]

PPW/models.py
from django.db import models

# Create your models here.

PPW/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def more(request):
    return render(request, 'more.html')

PPW/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>About Me</title>
    </head>

    <body>
        <table class="header">
            <tr>
                <td>
                    <h1 class="name">Aryuda Oktawyandra</h1>
                    <a href="{% url 'PPW:index' %}">
                        <h1 class="homepage">Homepage</h1>
                    </a>
                </td>
            </tr>
        </table>

        <h1 class="aboutme">About Me</h1>
        <table class="text">
            <tr>
                <td>
                    <article>I’m a college student of Computer Science at University of Indonesia. I’m a man of focus, commitment, and sheer will</article>
                    <article>Just contact me if you want to know more about me</article>
                    <article>Peace, love, and gaul ;)</article>
                </td>
            </tr>
        </table>
        
        <h1 class="project">Project</h1>
        <table class="airbus">
            <tr>
                <td>
                    <img class="airbuspic" src="https://profile.line-scdn.net/0m0e49d2db725190e555d410aa11cdb98a2971c06c40f7/preview" alt="Airbus">
                    <p class="judul">Airbus</p>
                    <p class="isi">Airbus is a service start-up that provides rental for school needs such as school hats, school ties, lab coats, print your schoolwork, and many more.
                        Unfortunately this start-up just available on my high school only.</p>
                </td>
            </tr>
        </table>

        <a href="{% url 'PPW:more' %}">
            <p class="more">More about me</p>
        </a>

    </body>

</html>

PPW/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Homepage</title>
    </head>

    <body>
        <table class="header">
            <tr>
                <td>
                    <h1 class="name">Aryuda Oktawyandra</h1>
                    <a href="{% url 'PPW:about' %}">
                        <h1 class="about">About Me</h1>
                    </a>
                </td>
            </tr>
        </table>

        <table class="awal">
            <tr>
                <td>
                    <table class="image">
                        <tr>
                            <td>
                                <img class="self" src="https://maung.id/static/3218f16a5414379bac2e0ca2bc5b348b/9f583/KR09.jpg" alt="Aryuda O.">
                                <a href="https://maung.id/aryuda.oktawyandra" target="_blank">
                                    <span class="source">Source</span>
                                </a>
                            </td>
                        </tr>
                    </table>  
                    <table class="first">
                        <tr>
                            <td>
                                <h2 class="hello">Hello People</h2>
                                <article class="welcome">My name is Yuda, and welcome to my web</article>
                                <article class="welcome">Please don’t leave your seat, and make sure to fasten your seat belt</article>
                                <article class="welcome">Enjoy your time :)</article>
                            </td>
                        </tr>
                    </table>    
                </td>
            </tr>
        </table>

        <h1 class="edu">Education Background</h1>
        <table class="background">
            <tr>
                <td>
                    <table class="smp">
                        <tr>
                            <td>
                                <h2 class="class">Junior High School</h2>
                                <img class="classpic" src="https://4.bp.blogspot.com/-o6pJdteu8C4/UOA_-7Q6PWI/AAAAAAAAJc8/9dj8WgFLCy0/s1600/LOGO+OSIS+SMP.png" alt="Logo SMP">
                                <h3 class="place">SMPN 91 Jakarta</h3>
                            </td>
                        </tr>
                    </table>
                    <table class="sma">
                        <tr>
                            <td>
                                <h2 class="class">Senior High School</h2>
                                <img class="classpic" src="https://1.bp.blogspot.com/-k1X-FZql9z4/UOA_sQfMy2I/AAAAAAAAJc0/OibdJLa5tAU/s1600/LOGO+OSIS+SMA.png" alt="Logo SMA">
                                <h3 class="place">SMAN 39 Jakarta</h3>
                            </td>
                        </tr>
                    </table>
                    <table class="kuliah">
                        <tr>
                            <td>
                                <h2 class="class">College University</h2>
                                <img class="UIpic" src="https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Makara_UI.png/1200px-Makara_UI.png" alt="Logo UI">
                                <h3 class="place">University of Indonesia</h3>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
            
        <br>
        <h1 class="contact">Contact Me</h1>

        <table class="excontact">
            <th>
                <td>
                    <a href="https://line.me/R/ti/p/aryuda145" target="_blank">
                        <img class="line" src="https://www.freepnglogos.com/uploads/line-messenger-logo-2.png" alt="Line">
                    </a>
                    <a href="https://wa.me/+6281212945027" target="_blank">
                        <img class="whatsapp" src="https://www.freepnglogos.com/uploads/whatsapp-logo-image-8.png" alt="Whatsapp">
                    </a>
                    <a href="https://id.linkedin.com/in/aryuda-oktawyandra-2703bb195" target="_blank">
                        <img class="linkedin" src="https://cdn.iconscout.com/icon/free/png-512/linkedin-circle-1868976-1583140.png" alt="LinkedIn">
                    </a>
                </td>
            </th>
        </table>
        <br>

    </body>

</html>

PPW/templates/more.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Organization</title>
    </head>

    <body>
        <table class="header">
            <tr>
                <td>
                    <h1 class="name">Aryuda Oktawyandra</h1>
                    <a href="{% url 'PPW:index' %}">
                        <h1 class="homepage">Homepage</h1>
                    </a>
                </td>
            </tr>
        </table>
        
        <h1 class="organization">Organization Experience</h1>
        <table class="compfest">
            <tr>
                <td>
                    <img class="pic" src="https://pbs.twimg.com/profile_images/1237361109960552449/ssdSXeSS_400x400.jpg" alt="Compfest">
                    <p class="judul">Compfest</p>
                    <p class="isi">COMPFEST is an annual one-stop IT event run by students of the Faculty of Computer Science, University of Indonesia.</p>
                </td>
            </tr>
        </table>

        <br><br>

        <table class="perak">
            <tr>
                <td>
                    <img class="pic" src="https://pbs.twimg.com/profile_images/1208613351615418369/tRyrgKyl_400x400.jpg" alt="PERAK">
                    <p class="judul">PERAK</p>
                    <p class="isi">PERAK is the biggest internal event at Faculty of Computer Science, University of Indonesia which aims to maintain a sense of kinship between elements</p>
                </td>
            </tr>
        </table>

        <a href="{% url 'PPW:about' %}">
            <p class="back">Back</p>
        </a>
        
    </body>

</html>